In [1]:
import pandas as pd
import numpy as np

In [3]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [8]:
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
556 2019-03-14        2422       18       3       2019
776 2019-08-18         704       13      10       2019
402 2018-11-05        4347       25     131       2018
134 2019-11-17        6049       16       1       2019
179 2019-01-15        4571       22       3       2019

In [16]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
661 2019-11-25        3042       28       1       2019             11
985 2018-12-08        5486       14       1       2018             12
281 2019-06-17        4379        4       1       2019              6
983 2019-08-02        6399        0       1       2019              8
101 2019-12-01         895       14      47       2019             12

In [19]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
375,2019-07-14,2002,1,3,2019,7,July
18,2019-06-12,5630,14,31,2019,6,June
50,2019-06-07,6137,3,3,2019,6,June
842,2018-07-23,2190,14,3,2018,7,July
328,2019-11-20,7467,23,2,2019,11,November

In [21]:
date['date_day_no'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day_no
82,2019-10-26,1985,14,13,2019,10,October,26
172,2019-06-24,5450,13,1,2019,6,June,24
764,2019-07-26,6850,1,2,2019,7,July,26
442,2019-06-04,963,13,1,2019,6,June,4
279,2019-12-05,2884,2,19,2019,12,December,5

In [23]:
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day_no,date_dow
821,2018-12-07,4996,5,6,2018,12,December,7,4
952,2018-08-18,6492,16,1,2018,8,August,18,5
470,2019-11-22,3125,1,69,2019,11,November,22,4
770,2018-09-10,6095,9,1,2018,9,September,10,0
289,2019-11-21,483,14,3,2019,11,November,21,3

In [25]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders'])
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day_no,date_dow,date_dow_name
971,2019-04-17,1233,16,18,2019,4,April,17,2,Wednesday
280,2018-08-18,6716,16,2,2018,8,August,18,5,Saturday
648,2018-10-08,564,25,1,2018,10,October,8,0,Monday
492,2019-06-24,2306,14,12,2019,6,June,24,0,Monday
203,2019-12-16,4033,4,1,2019,12,December,16,0,Monday

In [26]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day_no,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [30]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [31]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [32]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day_no,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [34]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 7, 24, 11, 37, 48, 866341)

In [35]:
today - date['date']

0     2418 days 11:37:48.866341
1     2900 days 11:37:48.866341
2     2831 days 11:37:48.866341
3     2533 days 11:37:48.866341
4     2756 days 11:37:48.866341
                 ...
995   2846 days 11:37:48.866341
996   2787 days 11:37:48.866341
997   2635 days 11:37:48.866341
998   2700 days 11:37:48.866341
999   2474 days 11:37:48.866341
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
(today - date['date']).dt.days

0      2418
1      2900
2      2831
3      2533
4      2756
       ...
995    2846
996    2787
997    2635
998    2700
999    2474
Name: date, Length: 1000, dtype: int64

In [38]:
np.round((today - date['date']) / np.timedelta64(1, 'm'),0)

0      3482618.0
1      4176698.0
2      4077338.0
3      3648218.0
4      3969338.0
         ...
995    4098938.0
996    4013978.0
997    3795098.0
998    3888698.0
999    3563258.0
Name: date, Length: 1000, dtype: float64

In [40]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [41]:
time['date'] = pd.to_datetime(time['date'])

In [42]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [45]:
today - time['date']

0     4604 days 10:47:48.866341
1     4468 days 11:57:48.866341
2     4954 days 11:16:48.866341
3     4256 days 11:06:48.866341
4     4653 days 12:26:48.866341
                 ...
995   5243 days 10:47:48.866341
996   4564 days 12:23:48.866341
997   5029 days 12:00:48.866341
998   5145 days 12:03:48.866341
999   4417 days 12:12:48.866341
Name: date, Length: 1000, dtype: timedelta64[ns]

In [47]:
(today - time['date']) / np.timedelta64(1, 's')

0      3.978245e+08
1      3.860783e+08
2      4.280662e+08
3      3.677584e+08
4      4.020640e+08
           ...
995    4.530341e+08
996    3.943742e+08
997    4.345488e+08
998    4.445714e+08
999    3.816728e+08
Name: date, Length: 1000, dtype: float64

In [48]:
(today - time['date']) / np.timedelta64(1, 'm')

0      6.630408e+06
1      6.434638e+06
2      7.134437e+06
3      6.129307e+06
4      6.701067e+06
           ...
995    7.550568e+06
996    6.572904e+06
997    7.242481e+06
998    7.409524e+06
999    6.361213e+06
Name: date, Length: 1000, dtype: float64

In [49]:
(today - time['date']) / np.timedelta64(1, 'h')

0      110506.796907
1      107243.963574
2      118907.280241
3      102155.113574
4      111684.446907
           ...
995    125842.796907
996    109548.396907
997    120708.013574
998    123492.063574
999    106020.213574
Name: date, Length: 1000, dtype: float64